#! /bin/sh

#bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d I II III IV V

bspc config border_width 3
bspc config top_padding  33

bspc config window_gap            10
bspc config split_ratio           0.50
bspc config focus_follows_pointer true

# autostart up applications 
#~/.config/eww/bar/launch_bar &
~/.config/polybar/launch.sh &
~/.config/bspwm/autostart &
sxhkd &
